#!/bin/bash

echo -e "$0 0.5
retrieve cell specific fastq reads from provided list of cell barcodes from single-cell RNA-seq data
(e.g. retrieved using WhichCells() function of Seurat R package)

contact: ricardo.santos@nms.unl.pt
------------------------------------------------
"

# USAGE STATEMENT
usage="\n
\$ bash subcell cell.barcodes folder_fastq/
\n 
\nThis tool takes two positional arguments (no flags): 
\n  - First argument is a file with the cell barcodes of interest.
\n  - Second argument is the folder containing the fastq.gz reads files"

# TESTING ARGUMENTS
if ! [[ -f $1 ]]; then 
    echo "WARNING: First argument is not a file" 
    echo -e $usage >&2; exit 1;
fi

if ! [[ -d $2 ]]; then
    echo "WARNING: Second argument is not a directory"
    echo -e $usage >&2; exit 1;
fi

outpath=$3
mkdir -p $outpath
cd $outpath
outpath=$PWD

threads=$4
if [[ -z $threads || $threads -lt 1 ]]; then
    threads=1
fi

# ACTIVATING CONDA ENVIRONMENT
# CONDA_PATH=$(conda info | grep -i 'base environment' | awk '{print$(4)}')
# CONDA_SH=$CONDA_PATH'/etc/profile.d/conda.sh'

# source $CONDA_SH
conda init $(echo $SHELL | awk -F'[/]' '{print$(NF)}') &> cmd.out
conda activate subcell &> cmd.out

# Input file with cell barcodes
input=$(readlink -f $1)
outfile=$(echo $1 | awk -F'[/]' '{print$(NF)}' | sed 's/\(.*\)\..*/\1/')
# Directory with the I1 R1 R2 fastq read files
dir=$(readlink -f $2)

# Get cell barcodes (CB)
# This is from our special case scRNA-seq experiment.
# Seurat filtered cell types contain the CBs in the following format:
# sample{1,2}-<Barcode>_1
# The following sed commands remove the non nucleotide info

awk -F'[_]' '{print$2}' $input | awk -F'[-]' '{print$1}' > "$outpath"/"$outfile"_barcodes.tmp

# Extract reads that belong to the cell barcode

ls $dir/*R1*.fastq.gz > R1files.txt
ls $dir/*R2*.fastq.gz > R2files.txt

if [[ $(ls $dir/*.fastq.gz | wc -l) == 0 ]]; then
    echo -e "Directory does not contain the required R1/R2 read files.
    Please provide the correct directory or make sure .fastq.gz files are compressed"
    exit 2
else
    if [[ $(ls $dir/*.fastq.gz | grep -E '*_R(1|2)_*' | wc -l) == 0 ]]; then
        echo -e "Directory does not contain the required R1/R2 read files.
        Please provide the correct directory or make sure .fastq.gz files are compressed"
        exit 2
    else
        for i in $(cat R1files.txt); do
            parallel -k --lb -j $threads -a "$outpath"/"$outfile".tmp fqtools find -s {} "$i" ">>" "$outpath"/"$outfile"_{}.tmp
        done

        for j in $(ls "$outpath"/"$outfile"_*.tmp); do
            cell_j=$(basename -- $j | awk -F'[.]' '{print$1}')
            cat "$j" | awk '/^@/ {print substr($0,2); }' | sed 's/\ 1:/\ 2:/g' > "$outpath"/"$cell_j".head
        done
        
        ls "$outpath"/*.head > "$outpath"/head-files.tmp
        for k in $(cat R2files.txt); do
            parallel -k --lb -j $threads -a "$outpath"/head-files.tmp filterbyname.sh include=t app=t in="$k" names={} out=stdout.fastq ">>" "$outpath"/"$outfile"_{}.fastq
        done
    fi
fi
rm *.txt *.tmp

gzip -r "$outpath"

# DEACTIVATE CONDA ENVIRONMENT
conda deactivate &> cmd.out
rm cmd.out
echo "Reads belonging to the provided barcodes were written in "$outpath"/"$outfile" with the format: "$outfile"_<barcode>.fastq.gz"
exit 1
