#!/bin/bash

echo -e "$0 0.5
retrieve cell specific fastq reads from provided list of cell barcodes from single-cell RNA-seq data
(e.g. retrieved using WhichCells() function of Seurat R package)

contact: ricardo.santos@nms.unl.pt
------------------------------------------------
"

# USAGE STATEMENT
usage="\n
\$ bash subcell cell.barcodes folder_fastq/
\n 
\nThis tool takes two positional arguments (no flags): 
\n  - First argument is a file with the cell barcodes of interest.
\n  - Second argument is the folder containing the fastq.gz reads files"

# TESTING ARGUMENTS
if ! [[ -f $1 ]]; then 
    echo "WARNING: First argument is not a file" 
    echo -e $usage >&2; exit 1;
fi

if ! [[ -d $2 ]]; then
    echo "WARNING: Second argument is not a directory"
    echo -e $usage >&2; exit 1;
fi

outpath=$3
mkdir -p $outpath
cd $outpath

threads=$4
if [[ -z $threads || $threads -lt 1 ]]; then
    threads=1
fi

# ACTIVATING CONDA ENVIRONMENT
CONDA_PATH=$(conda info | grep -i 'base environment' | awk '{print$(4)}')
CONDA_SH=$CONDA_PATH'/etc/profile.d/conda.sh'

source $CONDA_SH
conda init $(echo $SHELL | awk -F'[/]' '{print$(NF)}') &> /dev/null
conda activate subcell &> /dev/null

# Input file with cell barcodes
input=$(readlink -f $1)
outfile=$(echo $1 | awk -F'[/]' '{print$(NF)}' | sed 's/\(.*\)\..*/\1/')
# Directory with the I1 R1 R2 fastq read files
dir=$(readlink -f $2)

# Get cell barcodes (CB)
# This is from our special case scRNA-seq experiment.
# Seurat filtered cell types contain the CBs in the following format:
# sample{1,2}-<Barcode>_1
# The following sed commands remove the non nucleotide info

sed 's/^.*\(_.*-\).*$/\1/' $input | sed 's/-\|_//g' > "$outfile".tmp

# Extract reads that belong to the cell barcode

readlink -f $(ls $dir/*.fastq.gz) > files.txt
count=0
for i in $(cat "$outfile".tmp); do
    echo $i > "$i".txt
    if [[ $(ls $dir/*.fastq.gz | wc -l) == 0 ]]; then
        echo -e "Directory does not contain the required R1/R2 read files.
        Please provide the correct directory or make sure .fastq.gz files are compressed"
    else
        if [[ $(ls $dir/*.fastq.gz | grep -E '*_R(1|2)_*' | wc -l) == 0 ]]; then
            echo -e "Directory does not contain the required R1/R2 read files.
            Please provide the correct directory or make sure .fastq.gz files are compressed"
        else
            while read l
            do
                if ! [[ $(echo $l | grep -E '*_R1_*') == "" ]]; then
                    echo "Processing headers of provided barcodes:"
                    echo $(echo $l | awk -F'[/]' '{print$(NF)}')
                    fqtools find -f "$i".txt "$l" | awk '/^@/ {print $0}' | sed 's/@//g' | sed 's/\ 1:/\ 2:/g' >> "$i".head
                    wait
                    l2=$(echo $l | sed 's/_R1_/_R2_/g')
                    echo "Processing reads:"
                    echo $(echo $l2 | awk -F'[/]' '{print$(NF)}')
                    filterbyname.sh include=t app=t in="$l2" names="$i".head out="$outfile"_"$count"_"$i".fastq.gz &> /dev/null
                fi
            done < files.txt
            rm "$i".head
        fi
    fi
count=$((count+1))
done

rm files.txt

# DEACTIVATE CONDA ENVIRONMENT
conda deactivate &> /dev/null

echo "Reads belonging to the provided barcodes were written in "$2" using as "$outfile".fastq.gz"
